dist: trusty
sudo: false

language: node_js
node_js:
  - "8"
  
addons:
  chrome: stable

cache:
  directories:
     - $HOME/.composer/cache/files
     - $HOME/.npm
     - node_modules

install:
  - npm install

script:
  - "sed -ri \"s/clientId:[^,]*/clientId: '$clientId'/\" src/environments/environment*.ts"
  - npm run test -- --no-watch --no-progress --code-coverage --browsers=ChromeHeadlessCI
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
